# Generated by Django 5.2.7 on 2025-11-01 02:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementTaxe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee_fiscale', models.PositiveIntegerField(verbose_name='Année fiscale')),
                ('montant_du_ariary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant dû (Ariary)')),
                ('montant_paye_ariary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant payé (Ariary)')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('IMPAYE', 'Impayé'), ('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé'), ('EXONERE', 'Exonéré'), ('ANNULE', 'Annulé')], default='IMPAYE', max_length=20, verbose_name='Statut')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='ID de transaction')),
                ('methode_paiement', models.CharField(blank=True, choices=[('mvola', 'MVola'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('carte_bancaire', 'Carte bancaire')], max_length=30, null=True, verbose_name='Méthode de paiement')),
                ('details_paiement', models.JSONField(blank=True, default=dict, verbose_name='Détails du paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicule_plaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'Paiement de taxe',
                'verbose_name_plural': 'Paiements de taxes',
                'indexes': [models.Index(fields=['vehicule_plaque', 'annee_fiscale'], name='payments_pa_vehicul_bac3be_idx'), models.Index(fields=['statut'], name='payments_pa_statut_a39adc_idx'), models.Index(fields=['date_paiement'], name='payments_pa_date_pa_895dff_idx'), models.Index(fields=['transaction_id'], name='payments_pa_transac_408778_idx')],
                'unique_together': {('vehicule_plaque', 'annee_fiscale')},
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee_fiscale', models.PositiveIntegerField(verbose_name='Année fiscale')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Token de vérification')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('nombre_scans', models.PositiveIntegerField(default=0, verbose_name='Nombre de scans')),
                ('derniere_verification', models.DateTimeField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('vehicule_plaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'indexes': [models.Index(condition=models.Q(('est_actif', True)), fields=['token'], name='qr_token_actif_idx'), models.Index(fields=['vehicule_plaque', 'annee_fiscale'], name='payments_qr_vehicul_38803b_idx'), models.Index(condition=models.Q(('est_actif', True)), fields=['date_expiration'], name='qr_expiration_actif_idx')],
                'unique_together': {('vehicule_plaque', 'annee_fiscale')},
            },
        ),
    ]
