# Generated by Django 5.2.7 on 2025-11-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('vehicles', '0005_auto_20251102_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Event ID')),
                ('type', models.CharField(max_length=100, verbose_name="Type d'événement")),
                ('data', models.JSONField(verbose_name="Données de l'événement")),
                ('processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
            ],
            options={
                'verbose_name': 'Événement Webhook Stripe',
                'verbose_name_plural': 'Événements Webhook Stripe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='amount_stripe',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant en centimes (Stripe)'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de facturation'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='billing_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de facturation'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='currency_stripe',
            field=models.CharField(default='MGA', max_length=3, verbose_name='Devise Stripe'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Charge ID'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='stripe_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de création Stripe'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='stripe_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées Stripe'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stripe Payment Intent ID'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='stripe_payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Méthode de paiement Stripe'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='stripe_receipt_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL du reçu Stripe'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='stripe_status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('succeeded', 'Réussi'), ('failed', 'Échoué'), ('canceled', 'Annulé'), ('refunded', 'Remboursé'), ('partially_refunded', 'Partiellement remboursé')], max_length=30, null=True, verbose_name='Statut Stripe'),
        ),
        migrations.AddIndex(
            model_name='paiementtaxe',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__5351b1_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementtaxe',
            index=models.Index(fields=['stripe_status'], name='payments_pa_stripe__34d8df_idx'),
        ),
    ]
