# Generated by Django 5.2.7 on 2025-11-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_stripewebhookevent_paiementtaxe_amount_stripe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('development', 'Development'), ('production', 'Production')], max_length=20, unique=True)),
                ('publishable_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='MGA', max_length=10)),
                ('success_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cancel_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stripe configuration',
                'verbose_name_plural': 'Stripe configurations',
            },
        ),
    ]
