# Generated by Django 5.2.7 on 2025-11-08 02:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_stripeconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSystemConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Taux de commission par défaut pour les agents partenaires', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux de commission par défaut (%)')),
                ('dual_verification_threshold', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), help_text='Montant au-dessus duquel une approbation admin est requise', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Seuil de double vérification (Ariary)')),
                ('reconciliation_tolerance', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Écart acceptable lors de la réconciliation', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tolérance de réconciliation (Ariary)')),
                ('session_timeout_hours', models.IntegerField(default=12, help_text="Nombre d'heures avant qu'une session ouverte expire", verbose_name="Délai d'expiration de session (heures)")),
                ('void_time_limit_minutes', models.IntegerField(default=30, help_text='Temps maximum pour annuler une transaction', verbose_name="Délai d'annulation (minutes)")),
                ('receipt_footer_text', models.TextField(blank=True, help_text='Texte personnalisé pour le pied de page des reçus', verbose_name='Texte de pied de page du reçu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du système de paiement en espèces',
                'verbose_name_plural': 'Configuration du système de paiement en espèces',
            },
        ),
        migrations.AlterField(
            model_name='paiementtaxe',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('mvola', 'MVola'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('carte_bancaire', 'Carte bancaire'), ('cash', 'Espèces')], max_length=30, null=True, verbose_name='Méthode de paiement'),
        ),
        migrations.CreateModel(
            name='AgentPartenaireProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(help_text="Identifiant unique de l'agent", max_length=50, unique=True, verbose_name='ID Agent')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('collection_location', models.CharField(help_text="Emplacement où l'agent collecte les paiements", max_length=200, verbose_name='Lieu de collecte')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Laissez vide pour utiliser le taux par défaut', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Taux de commission personnalisé (%)')),
                ('use_default_commission', models.BooleanField(default=True, verbose_name='Utiliser le taux de commission par défaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_partenaire_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Agent Partenaire',
                'verbose_name_plural': 'Profils Agents Partenaires',
            },
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to='payments.agentpartenaireprofile', verbose_name='Collecté par'),
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de session')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Solde d'ouverture (Ariary)")),
                ('opening_time', models.DateTimeField(auto_now_add=True, verbose_name="Heure d'ouverture")),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Solde de clôture (Ariary)')),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Solde attendu (Ariary)')),
                ('closing_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de clôture')),
                ('discrepancy_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Montant de l'écart (Ariary)")),
                ('discrepancy_notes', models.TextField(blank=True, verbose_name="Notes sur l'écart")),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Commission totale (Ariary)')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('reconciled', 'Réconcilié')], default='open', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='payments.agentpartenaireprofile', verbose_name='Collecteur')),
            ],
            options={
                'verbose_name': 'Session de collecte',
                'verbose_name_plural': 'Sessions de collecte',
                'ordering': ['-opening_time'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de transaction')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('vehicle_plate', models.CharField(max_length=20, verbose_name="Plaque d'immatriculation")),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant de la taxe (Ariary)')),
                ('amount_tendered', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant remis (Ariary)')),
                ('change_given', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monnaie rendue (Ariary)')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant de la commission (Ariary)')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Nécessite une approbation')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'approbation")),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='Heure de transaction')),
                ('receipt_printed', models.BooleanField(default=False, verbose_name='Reçu imprimé')),
                ('receipt_print_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'impression du reçu")),
                ('is_voided', models.BooleanField(default=False, verbose_name='Annulé')),
                ('void_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'annulation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.agentpartenaireprofile', verbose_name='Collecteur')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_transaction', to='payments.paiementtaxe', verbose_name='Paiement')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.cashsession', verbose_name='Session')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
            ],
            options={
                'verbose_name': 'Transaction en espèces',
                'verbose_name_plural': 'Transactions en espèces',
                'ordering': ['-transaction_time'],
            },
        ),
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de reçu')),
                ('vehicle_registration', models.CharField(max_length=20, verbose_name='Immatriculation du véhicule')),
                ('vehicle_owner', models.CharField(max_length=200, verbose_name='Propriétaire du véhicule')),
                ('tax_year', models.IntegerField(verbose_name='Année fiscale')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant de la taxe (Ariary)')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant payé (Ariary)')),
                ('change_given', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monnaie rendue (Ariary)')),
                ('collector_name', models.CharField(max_length=200, verbose_name='Nom du collecteur')),
                ('collector_id', models.CharField(max_length=50, verbose_name='ID du collecteur')),
                ('payment_date', models.DateTimeField(verbose_name='Date de paiement')),
                ('qr_code_data', models.TextField(verbose_name='Données du QR code')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='Est un duplicata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('original_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='payments.cashreceipt', verbose_name='Reçu original')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_receipts', to='payments.qrcode', verbose_name='QR Code')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.cashtransaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Reçu en espèces',
                'verbose_name_plural': 'Reçus en espèces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('session_open', 'Ouverture de session'), ('session_close', 'Fermeture de session'), ('transaction_create', 'Création de transaction'), ('transaction_approve', 'Approbation de transaction'), ('transaction_void', 'Annulation de transaction'), ('receipt_print', 'Impression de reçu'), ('receipt_reprint', 'Réimpression de reçu'), ('reconciliation', 'Réconciliation'), ('config_change', 'Modification de configuration')], max_length=50, verbose_name="Type d'action")),
                ('action_data', models.JSONField(default=dict, verbose_name="Données de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('previous_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash précédent')),
                ('current_hash', models.CharField(max_length=64, verbose_name='Hash actuel')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payments.cashsession', verbose_name='Session')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='payments.cashtransaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': "Journal d'audit en espèces",
                'verbose_name_plural': "Journaux d'audit en espèces",
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant de la taxe (Ariary)')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux de commission (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant de la commission (Ariary)')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut de paiement')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='payments.agentpartenaireprofile', verbose_name='Collecteur')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commissions', to=settings.AUTH_USER_MODEL, verbose_name='Payé par')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='payments.cashsession', verbose_name='Session')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='payments.cashtransaction', verbose_name='Transaction')),
            ],
            options={
                'verbose_name': 'Enregistrement de commission',
                'verbose_name_plural': 'Enregistrements de commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentpartenaireprofile',
            index=models.Index(fields=['agent_id'], name='payments_ag_agent_i_29f730_idx'),
        ),
        migrations.AddIndex(
            model_name='agentpartenaireprofile',
            index=models.Index(fields=['is_active'], name='payments_ag_is_acti_12a8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['collector', 'status'], name='payments_ca_collect_21aa2e_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['session_number'], name='payments_ca_session_852304_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['opening_time'], name='payments_ca_opening_723e14_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['status'], name='payments_ca_status_0d18c4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['session', 'transaction_time'], name='payments_ca_session_844c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['transaction_number'], name='payments_ca_transac_7b3d89_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['collector', 'transaction_time'], name='payments_ca_collect_2bd46c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['requires_approval'], name='payments_ca_require_817d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['is_voided'], name='payments_ca_is_void_39d376_idx'),
        ),
        migrations.AddIndex(
            model_name='cashreceipt',
            index=models.Index(fields=['receipt_number'], name='payments_ca_receipt_d9aca3_idx'),
        ),
        migrations.AddIndex(
            model_name='cashreceipt',
            index=models.Index(fields=['transaction'], name='payments_ca_transac_578093_idx'),
        ),
        migrations.AddIndex(
            model_name='cashreceipt',
            index=models.Index(fields=['vehicle_registration', 'tax_year'], name='payments_ca_vehicle_0b841f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashauditlog',
            index=models.Index(fields=['timestamp'], name='payments_ca_timesta_7d309f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='payments_ca_user_id_2db22e_idx'),
        ),
        migrations.AddIndex(
            model_name='cashauditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='payments_ca_action__169448_idx'),
        ),
        migrations.AddIndex(
            model_name='cashauditlog',
            index=models.Index(fields=['session'], name='payments_ca_session_763b34_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['collector', 'payment_status'], name='payments_co_collect_941940_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['session'], name='payments_co_session_d34b20_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrecord',
            index=models.Index(fields=['payment_status'], name='payments_co_payment_5cc403_idx'),
        ),
    ]
