# Generated by Django 5.2.7 on 2025-11-08 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_cashsystemconfig_alter_paiementtaxe_methode_paiement_and_more'),
        ('vehicles', '0009_vehicule_couleur_vehicule_marque_vehicule_modele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementtaxe',
            name='mvola_customer_msisdn',
            field=models.CharField(blank=True, help_text='Customer phone number for MVola payment', max_length=15, null=True, verbose_name='Customer MSISDN'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='mvola_gateway_fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual fees charged by MVola gateway', max_digits=12, null=True, verbose_name='MVola Gateway Fees'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='mvola_platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='3% platform fee charged to customer', max_digits=12, null=True, verbose_name='MVola Platform Fee (3%)'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='mvola_server_correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='Transaction identifier from MVola', max_length=100, null=True, verbose_name='MVola Server Correlation ID'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='mvola_status',
            field=models.CharField(blank=True, choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué')], max_length=20, null=True, verbose_name='Statut MVola'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='mvola_transaction_reference',
            field=models.CharField(blank=True, help_text='Final transaction reference from MVola', max_length=100, null=True, verbose_name='MVola Transaction Reference'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='mvola_x_correlation_id',
            field=models.CharField(blank=True, help_text='Request correlation ID generated by our system', max_length=100, null=True, verbose_name='MVola X-Correlation-ID'),
        ),
        migrations.AlterField(
            model_name='cashreceipt',
            name='qr_code',
            field=models.ForeignKey(blank=True, help_text='QR code partagé avec tous les types de paiement pour ce véhicule et année fiscale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_receipts', to='payments.qrcode', verbose_name='QR Code'),
        ),
        migrations.AddIndex(
            model_name='paiementtaxe',
            index=models.Index(fields=['mvola_server_correlation_id'], name='payments_pa_mvola_s_721d6b_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementtaxe',
            index=models.Index(fields=['mvola_status'], name='payments_pa_mvola_s_f0d3e1_idx'),
        ),
    ]
