# Generated by Django 5.2.7 on 2025-11-13 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contraventions', '0001_modify_paiementtaxe_for_contraventions'),
        ('payments', '0007_migrate_mvola_data_from_administration'),
        ('vehicles', '0009_vehicule_couleur_vehicule_marque_vehicule_modele_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paiementtaxe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='contravention',
            field=models.ForeignKey(blank=True, help_text='Contravention associée si type_paiement est AMENDE_CONTRAVENTION', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='contraventions.contravention', verbose_name='Contravention'),
        ),
        migrations.AddField(
            model_name='paiementtaxe',
            name='type_paiement',
            field=models.CharField(choices=[('TAXE_VEHICULE', 'Taxe véhicule'), ('AMENDE_CONTRAVENTION', 'Amende contravention')], default='TAXE_VEHICULE', help_text='Type de paiement: taxe véhicule ou amende contravention', max_length=30, verbose_name='Type de paiement'),
        ),
        migrations.AddIndex(
            model_name='paiementtaxe',
            index=models.Index(fields=['type_paiement'], name='payments_pa_type_pa_a56914_idx'),
        ),
        migrations.AddIndex(
            model_name='paiementtaxe',
            index=models.Index(fields=['contravention'], name='payments_pa_contrav_1af564_idx'),
        ),
        migrations.AddConstraint(
            model_name='paiementtaxe',
            constraint=models.UniqueConstraint(condition=models.Q(('type_paiement', 'TAXE_VEHICULE')), fields=('vehicule_plaque', 'annee_fiscale'), name='unique_vehicle_tax_per_year'),
        ),
    ]
