# Generated by Django 5.2.7 on 2025-11-23 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_update_qrcode_for_contraventions'),
        ('vehicles', '0014_alter_grilletarifaire_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qrcode',
            new_name='payments_qr_code_c30dce_idx',
            old_name='payments_qr_code_idx',
        ),
        migrations.RenameIndex(
            model_name='qrcode',
            new_name='payments_qr_type_co_ee73b0_idx',
            old_name='payments_qr_type_co_idx',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Token de vérification'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='vehicule_plaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='vehicles.vehicule'),
        ),
    ]
