# Generated by Django 5.2.7 on 2025-11-01 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_badge', models.CharField(max_length=20, unique=True, verbose_name='Numéro de badge')),
                ('zone_affectation', models.CharField(max_length=100, verbose_name="Zone d'affectation")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent de vérification',
                'verbose_name_plural': 'Agents de vérification',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True, verbose_name='Clé de configuration')),
                ('type_config', models.CharField(choices=[('taux_taxe', 'Taux de taxe'), ('duree_validite_qr', 'Durée validité QR (jours)'), ('montant_minimum_paiement', 'Montant minimum paiement'), ('frais_transaction', 'Frais de transaction (%)'), ('email_admin', 'Email administrateur'), ('sms_api_key', 'Clé API SMS'), ('mobile_money_config', 'Configuration Mobile Money')], max_length=50, verbose_name='Type de configuration')),
                ('valeur', models.TextField(verbose_name='Valeur')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configurations système',
            },
        ),
        migrations.CreateModel(
            name='StatistiquesPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_statistique', models.CharField(choices=[('utilisateurs_actifs', 'Utilisateurs actifs'), ('vehicules_enregistres', 'Véhicules enregistrés'), ('paiements_jour', 'Paiements du jour'), ('revenus_jour', 'Revenus du jour'), ('qr_generes', 'QR codes générés'), ('verifications_qr', 'Vérifications QR')], max_length=50, verbose_name='Type de statistique')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valeur')),
                ('date_statistique', models.DateField(verbose_name='Date de la statistique')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Statistique plateforme',
                'verbose_name_plural': 'Statistiques plateforme',
                'ordering': ['-date_statistique', 'type_statistique'],
                'indexes': [models.Index(fields=['type_statistique', 'date_statistique'], name='administrat_type_st_48ee36_idx'), models.Index(fields=['date_statistique'], name='administrat_date_st_edf0c0_idx')],
                'unique_together': {('type_statistique', 'date_statistique')},
            },
        ),
        migrations.CreateModel(
            name='VerificationQR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut_verification', models.CharField(choices=[('valide', 'Valide'), ('expire', 'Expiré'), ('invalide', 'Invalide'), ('deja_utilise', 'Déjà utilisé')], max_length=20, verbose_name='Statut de vérification')),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('localisation_gps', models.JSONField(blank=True, help_text='Coordonnées GPS de la vérification', null=True, verbose_name='Localisation GPS')),
                ('notes', models.TextField(blank=True, verbose_name='Notes de vérification')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='administration.agentverification')),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='payments.qrcode')),
            ],
            options={
                'verbose_name': 'Vérification QR',
                'verbose_name_plural': 'Vérifications QR',
                'ordering': ['-date_verification'],
            },
        ),
        migrations.AddIndex(
            model_name='agentverification',
            index=models.Index(fields=['numero_badge'], name='administrat_numero__ff1812_idx'),
        ),
        migrations.AddIndex(
            model_name='agentverification',
            index=models.Index(fields=['zone_affectation'], name='administrat_zone_af_de4c46_idx'),
        ),
        migrations.AddIndex(
            model_name='agentverification',
            index=models.Index(fields=['est_actif'], name='administrat_est_act_7e932b_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationsysteme',
            index=models.Index(fields=['cle'], name='administrat_cle_75481f_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationsysteme',
            index=models.Index(fields=['type_config'], name='administrat_type_co_44150a_idx'),
        ),
        migrations.AddIndex(
            model_name='configurationsysteme',
            index=models.Index(fields=['est_actif'], name='administrat_est_act_207f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationqr',
            index=models.Index(fields=['agent'], name='administrat_agent_i_ddfb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationqr',
            index=models.Index(fields=['qr_code'], name='administrat_qr_code_ee9160_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationqr',
            index=models.Index(fields=['statut_verification'], name='administrat_statut__e1389d_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationqr',
            index=models.Index(fields=['date_verification'], name='administrat_date_ve_1f72a8_idx'),
        ),
    ]
