# Generated by Django 5.2.7 on 2025-11-01 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('permissions', models.JSONField(default=dict, help_text="Format: {'module': ['view', 'create', 'edit', 'delete']}", verbose_name='Permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permission_groups', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('users', models.ManyToManyField(blank=True, related_name='custom_permission_groups', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs')),
            ],
            options={
                'verbose_name': 'Groupe de permissions',
                'verbose_name_plural': 'Groupes de permissions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Clé de session')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session administrateur',
                'verbose_name_plural': 'Sessions administrateurs',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='administrat_user_id_788bba_idx'), models.Index(fields=['session_key'], name='administrat_session_c2b3b6_idx'), models.Index(fields=['last_activity'], name='administrat_last_ac_0e5e8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.CharField(blank=True, max_length=32, verbose_name='TOTP Secret')),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA activé')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='Codes de secours')),
                ('ip_whitelist', models.JSONField(blank=True, default=list, help_text="Liste des adresses IP autorisées (format: ['192.168.1.1', '10.0.0.0/24'])", verbose_name='Liste blanche IP')),
                ('is_ip_whitelist_enabled', models.BooleanField(default=False, verbose_name='Liste blanche IP activée')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP de connexion')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Tentatives de connexion échouées')),
                ('account_locked_until', models.DateTimeField(blank=True, null=True, verbose_name="Compte verrouillé jusqu'à")),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='Dernier changement de mot de passe')),
                ('theme_preference', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=10, verbose_name='Thème préféré')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil administrateur',
                'verbose_name_plural': 'Profils administrateurs',
                'indexes': [models.Index(fields=['user'], name='administrat_user_id_ed3da2_idx'), models.Index(fields=['is_2fa_enabled'], name='administrat_is_2fa__6d4aff_idx'), models.Index(fields=['last_login_ip'], name='administrat_last_lo_f09251_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50, verbose_name="ID de l'objet")),
                ('version_number', models.IntegerField(verbose_name='Numéro de version')),
                ('data_snapshot', models.JSONField(verbose_name='Snapshot des données')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Modifié le')),
                ('change_reason', models.TextField(blank=True, verbose_name='Raison du changement')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Type de contenu')),
            ],
            options={
                'verbose_name': 'Version de données',
                'verbose_name_plural': 'Versions de données',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='administrat_content_d6f2c4_idx'), models.Index(fields=['changed_at'], name='administrat_changed_16e33a_idx')],
                'unique_together': {('content_type', 'object_id', 'version_number')},
            },
        ),
    ]
