# Generated by Django 5.2.7 on 2025-11-07 06:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_permissiongroup_adminsession_adminuserprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom descriptif pour identifier cette configuration SMTP', max_length=100, unique=True, verbose_name='Nom de la configuration')),
                ('host', models.CharField(help_text='Exemple: smtp.gmail.com, smtp.office365.com', max_length=255, verbose_name='Serveur SMTP')),
                ('port', models.IntegerField(default=587, help_text='Port standard: 587 (TLS), 465 (SSL), 25 (non sécurisé)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Port SMTP')),
                ('encryption', models.CharField(choices=[('none', 'Aucun'), ('tls', 'TLS'), ('ssl', 'SSL')], default='tls', max_length=10, verbose_name='Type de chiffrement')),
                ('username', models.CharField(help_text="Adresse email ou nom d'utilisateur SMTP", max_length=255, verbose_name="Nom d'utilisateur")),
                ('password', models.CharField(help_text="Mot de passe ou mot de passe d'application", max_length=255, verbose_name='Mot de passe')),
                ('from_email', models.EmailField(help_text='Adresse email qui apparaîtra comme expéditeur', max_length=254, verbose_name='Email expéditeur')),
                ('from_name', models.CharField(default='Tax Collector', help_text='Nom qui apparaîtra comme expéditeur', max_length=100, verbose_name="Nom de l'expéditeur")),
                ('reply_to_email', models.EmailField(blank=True, help_text='Adresse email pour les réponses (optionnel)', max_length=254, verbose_name='Email de réponse')),
                ('is_active', models.BooleanField(default=False, help_text='Une seule configuration peut être active à la fois', verbose_name='Configuration active')),
                ('is_verified', models.BooleanField(default=False, help_text='Indique si la configuration a été testée avec succès', verbose_name='Configuration vérifiée')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernière date de test')),
                ('last_test_result', models.TextField(blank=True, verbose_name='Résultat du dernier test')),
                ('daily_limit', models.IntegerField(default=500, help_text="Nombre maximum d'emails par jour (0 = illimité)", validators=[django.core.validators.MinValueValidator(0)], verbose_name="Limite quotidienne d'emails")),
                ('emails_sent_today', models.IntegerField(default=0, verbose_name="Emails envoyés aujourd'hui")),
                ('last_reset_date', models.DateField(auto_now_add=True, verbose_name='Dernière réinitialisation du compteur')),
                ('description', models.TextField(blank=True, help_text='Notes ou description de cette configuration', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smtp_configs_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smtp_configs_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration SMTP',
                'verbose_name_plural': 'Configurations SMTP',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('subject', models.CharField(max_length=255, verbose_name='Sujet')),
                ('body', models.TextField(verbose_name='Corps du message')),
                ('html_body', models.TextField(blank=True, verbose_name='Corps HTML')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échoué'), ('bounced', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('email_type', models.CharField(blank=True, help_text='Ex: reminder, notification, verification', max_length=50, verbose_name="Type d'email")),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name="Type d'objet lié")),
                ('related_object_id', models.CharField(blank=True, max_length=50, verbose_name="ID de l'objet lié")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('smtp_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='administration.smtpconfiguration', verbose_name='Configuration SMTP')),
            ],
            options={
                'verbose_name': "Journal d'email",
                'verbose_name_plural': "Journaux d'emails",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smtpconfiguration',
            index=models.Index(fields=['is_active'], name='administrat_is_acti_76a52f_idx'),
        ),
        migrations.AddIndex(
            model_name='smtpconfiguration',
            index=models.Index(fields=['is_verified'], name='administrat_is_veri_110c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient'], name='administrat_recipie_d73e36_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status'], name='administrat_status_a2ff3c_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['email_type'], name='administrat_email_t_50d54a_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['created_at'], name='administrat_created_ccb196_idx'),
        ),
    ]
