# Generated by Django 5.2.7 on 2025-11-08 17:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_smtpconfiguration_emaillog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MvolaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom descriptif pour identifier cette configuration MVola', max_length=100, unique=True, verbose_name='Nom de la configuration')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Test)'), ('production', 'Production (Live)')], default='sandbox', help_text='Sandbox pour les tests, Production pour les paiements réels', max_length=20, verbose_name='Environnement')),
                ('consumer_key', models.CharField(help_text="Clé d'API fournie par MVola (aussi appelée Client ID)", max_length=255, verbose_name='Client ID (Consumer Key)')),
                ('consumer_secret', models.CharField(help_text="Secret d'API fourni par MVola", max_length=255, verbose_name='Client Secret (Consumer Secret)')),
                ('merchant_msisdn', models.CharField(help_text='Numéro de téléphone MVola du marchand (ex: 0343151968)', max_length=20, verbose_name='Merchant Number (MSISDN)')),
                ('merchant_name', models.CharField(default='TaxCollector', help_text='Nom qui apparaîtra dans les transactions MVola', max_length=100, verbose_name='Nom du marchand')),
                ('base_url', models.URLField(blank=True, help_text="Laissez vide pour utiliser l'URL par défaut selon l'environnement", max_length=255, verbose_name="URL de base de l'API")),
                ('callback_url', models.URLField(blank=True, help_text='URL pour recevoir les notifications de statut de paiement', max_length=255, verbose_name='URL de callback')),
                ('min_amount', models.DecimalField(decimal_places=2, default=100, help_text='Montant minimum autorisé pour un paiement (Ariary)', max_digits=10, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(decimal_places=2, default=5000000, help_text='Montant maximum autorisé pour un paiement (Ariary)', max_digits=10, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Montant maximum')),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=3.0, help_text='Pourcentage de frais ajouté au montant de la taxe', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Frais de plateforme (%)')),
                ('logo', models.ImageField(blank=True, help_text='Logo à afficher sur les pages de paiement', null=True, upload_to='payment_gateways/mvola/', verbose_name='Logo MVola')),
                ('is_active', models.BooleanField(default=False, help_text='Une seule configuration peut être active à la fois', verbose_name='Configuration active')),
                ('is_enabled', models.BooleanField(default=True, help_text='Active ou désactive les paiements MVola sur la plateforme', verbose_name='MVola activé')),
                ('is_verified', models.BooleanField(default=False, help_text='Indique si la configuration a été testée avec succès', verbose_name='Configuration vérifiée')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernière date de test')),
                ('last_test_result', models.TextField(blank=True, verbose_name='Résultat du dernier test')),
                ('total_transactions', models.IntegerField(default=0, help_text='Nombre total de transactions effectuées', verbose_name='Total des transactions')),
                ('successful_transactions', models.IntegerField(default=0, verbose_name='Transactions réussies')),
                ('failed_transactions', models.IntegerField(default=0, verbose_name='Transactions échouées')),
                ('total_amount_processed', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant total traité (Ariary)')),
                ('description', models.TextField(blank=True, help_text='Notes ou description de cette configuration', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvola_configs_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvola_configs_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration MVola',
                'verbose_name_plural': 'Configurations MVola',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='administrat_is_acti_789336_idx'), models.Index(fields=['is_enabled'], name='administrat_is_enab_becbd2_idx'), models.Index(fields=['environment'], name='administrat_environ_e16d59_idx')],
            },
        ),
    ]
