# Generated by Django 5.2.7 on 2025-11-09 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_add_mvola_configuration'),
        ('payments', '0007_migrate_mvola_data_from_administration'),  # Ensure data is migrated first
    ]

    operations = [
        migrations.DeleteModel(
            name='MvolaConfiguration',
        ),
    ]
