# Generated by Django 5.2.7 on 2025-11-01 02:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PAYMENT', 'Paiement'), ('VERIFICATION', 'Vérification')], max_length=50)),
                ('table_concernee', models.CharField(max_length=50, verbose_name='Table concernée')),
                ('objet_id', models.CharField(blank=True, max_length=50, verbose_name="ID de l'objet")),
                ('donnees_avant', models.JSONField(blank=True, null=True, verbose_name='Données avant')),
                ('donnees_apres', models.JSONField(blank=True, null=True, verbose_name='Données après')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID de session')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['user', 'date_action'], name='core_auditl_user_id_4c17f9_idx'), models.Index(fields=['action', 'date_action'], name='core_auditl_action_57cfb7_idx'), models.Index(fields=['table_concernee', 'objet_id'], name='core_auditl_table_c_7cd977_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('numero_contribuable', models.CharField(max_length=50, unique=True, verbose_name='Numéro de contribuable')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('contact_principal', models.CharField(blank=True, max_length=100, verbose_name='Contact principal')),
                ('secteur_activite', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil entreprise',
                'verbose_name_plural': 'Profils entreprises',
                'indexes': [models.Index(fields=['numero_contribuable'], name='core_entrep_numero__b9836e_idx'), models.Index(fields=['nom_entreprise'], name='core_entrep_nom_ent_e47073_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?261\\d{9}$', 'Format: +261xxxxxxxxx')])),
                ('est_entreprise', models.BooleanField(default=False, verbose_name='Est une entreprise')),
                ('langue_preferee', models.CharField(choices=[('fr', 'Français'), ('mg', 'Malagasy')], default='fr', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'indexes': [models.Index(fields=['telephone'], name='core_userpr_telepho_ee0e58_idx'), models.Index(fields=['est_entreprise'], name='core_userpr_est_ent_3bda08_idx')],
            },
        ),
    ]
