# Generated by Django 5.2.7 on 2025-11-01 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='Numéro fiscal (NIF)')),
                ('business_registration_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'immatriculation")),
                ('industry_sector', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
                ('fleet_size', models.IntegerField(default=0, verbose_name='Taille de la flotte')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil entreprise',
                'verbose_name_plural': 'Profils entreprises',
            },
        ),
        migrations.CreateModel(
            name='EmergencyServiceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('service_type', models.CharField(choices=[('ambulance', "Service d'ambulance"), ('fire', 'Sapeurs-pompiers'), ('rescue', 'Service de secours'), ('medical', "Service médical d'urgence")], max_length=50, verbose_name='Type de service')),
                ('official_license', models.CharField(blank=True, max_length=100, verbose_name='Licence officielle')),
                ('department_contact', models.CharField(blank=True, max_length=100, verbose_name='Contact du département')),
                ('verification_document_url', models.URLField(blank=True, max_length=500, verbose_name='Document de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Profil service d'urgence",
                'verbose_name_plural': "Profils services d'urgence",
            },
        ),
        migrations.CreateModel(
            name='GovernmentAdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100, verbose_name='Département')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='ID employé')),
                ('access_level', models.IntegerField(choices=[(1, 'Niveau 1'), (2, 'Niveau 2'), (3, 'Niveau 3'), (4, 'Niveau 4'), (5, 'Niveau 5')], default=1, verbose_name="Niveau d'accès")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil administrateur gouvernemental',
                'verbose_name_plural': 'Profils administrateurs gouvernementaux',
            },
        ),
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'identité")),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil individuel',
                'verbose_name_plural': 'Profils individuels',
            },
        ),
        migrations.CreateModel(
            name='LawEnforcementProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de badge')),
                ('department', models.CharField(max_length=100, verbose_name='Département')),
                ('rank', models.CharField(blank=True, max_length=50, verbose_name='Grade')),
                ('jurisdiction', models.CharField(blank=True, max_length=100, verbose_name='Juridiction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Profil forces de l'ordre",
                'verbose_name_plural': "Profils forces de l'ordre",
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('identity', "Pièce d'identité"), ('business_license', 'Licence commerciale'), ('tax_certificate', 'Certificat fiscal'), ('official_authorization', 'Autorisation officielle'), ('badge_photo', 'Photo de badge'), ('department_letter', 'Lettre du département')], max_length=50, verbose_name='Type de document')),
                ('file_url', models.URLField(max_length=500, verbose_name='URL du fichier')),
                ('verification_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('under_review', "En cours d'examen")], default='pending', max_length=20, verbose_name='Statut de vérification')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Téléchargé le')),
            ],
            options={
                'verbose_name': 'Document de vérification',
                'verbose_name_plural': 'Documents de vérification',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Individual Citizen'), ('company', 'Company/Business'), ('emergency', 'Emergency Service Provider'), ('government', 'Government Administrator'), ('law_enforcement', 'Law Enforcement Officer')], default='individual', max_length=20, verbose_name="Type d'utilisateur"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('under_review', 'Under Review')], default='pending', max_length=20, verbose_name='Statut de vérification'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_type'], name='core_userpr_user_ty_baccfd_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['verification_status'], name='core_userpr_verific_9ab6af_idx'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='emergencyserviceprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_profile', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='governmentadminprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='government_profile', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='lawenforcementprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='law_enforcement_profile', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['tax_id'], name='core_compan_tax_id_8c1062_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['company_name'], name='core_compan_company_11108b_idx'),
        ),
        migrations.AddIndex(
            model_name='lawenforcementprofile',
            index=models.Index(fields=['badge_number'], name='core_lawenf_badge_n_61b95c_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['verification_status'], name='core_verifi_verific_3a7150_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationdocument',
            index=models.Index(fields=['document_type'], name='core_verifi_documen_ac55b2_idx'),
        ),
    ]
