# Generated by Django 5.2.7 on 2025-11-10 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_user_types(apps, schema_editor):
    """Migre les anciens types d'utilisateurs vers les nouveaux"""
    UserProfile = apps.get_model('core', 'UserProfile')
    
    # Migrer emergency -> public_institution
    UserProfile.objects.filter(user_type='emergency').update(user_type='public_institution')
    
    # Migrer government -> public_institution
    UserProfile.objects.filter(user_type='government').update(user_type='public_institution')
    
    # Migrer law_enforcement -> public_institution
    UserProfile.objects.filter(user_type='law_enforcement').update(user_type='public_institution')


def reverse_migration(apps, schema_editor):
    """Migration inverse (si nécessaire)"""
    UserProfile = apps.get_model('core', 'UserProfile')
    
    # Note: On ne peut pas distinguer les sous-types après migration
    # Cette fonction est à utiliser avec précaution
    # Par défaut, on migre tout vers 'government' car c'était le type le plus permissif
    UserProfile.objects.filter(user_type='public_institution').update(user_type='government')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_profile_picture'),
    ]

    operations = [
        # Step 1: Increase max_length and add new choices temporarily (keep old ones for migration)
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(
                choices=[
                    ('individual', 'Particulier (Citoyen)'),
                    ('company', 'Entreprise/Société'),
                    ('public_institution', 'Administration Publique et Institution'),
                    ('international_organization', 'Organisation Internationale'),
                    # Keep old types temporarily for migration
                    ('emergency', 'Emergency Service Provider'),
                    ('government', 'Government Administrator'),
                    ('law_enforcement', 'Law Enforcement Officer'),
                ],
                default='individual',
                max_length=30,
                verbose_name="Type d'utilisateur"
            ),
        ),
        # Step 2: Migrate existing data
        migrations.RunPython(migrate_user_types, reverse_migration),
        # Step 3: Update choices to remove old types (after data migration)
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('individual', 'Particulier (Citoyen)'), ('company', 'Entreprise/Société'), ('public_institution', 'Administration Publique et Institution'), ('international_organization', 'Organisation Internationale')], default='individual', max_length=30, verbose_name="Type d'utilisateur"),
        ),
        migrations.CreateModel(
            name='InternationalOrganizationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('organization_type', models.CharField(choices=[('ambassade', 'Ambassade'), ('consulat', 'Consulat'), ('mission_diplomatique', 'Mission diplomatique'), ('organisation_internationale', 'Organisation internationale (ONU, etc.)'), ('ong_internationale', 'ONG internationale'), ('autre', 'Autre organisation sous convention internationale')], max_length=50, verbose_name="Type d'organisation")),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name="Pays d'origine")),
                ('convention_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de convention')),
                ('diplomatic_immunity', models.BooleanField(default=False, verbose_name='Immunité diplomatique')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Personne de contact')),
                ('official_document_url', models.URLField(blank=True, max_length=500, verbose_name='Document officiel (convention, accord)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='international_organization_profile', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Profil Organisation Internationale',
                'verbose_name_plural': 'Profils Organisations Internationales',
                'indexes': [models.Index(fields=['organization_type'], name='core_intern_organiz_ffd80f_idx'), models.Index(fields=['organization_name'], name='core_intern_organiz_59f215_idx'), models.Index(fields=['country_of_origin'], name='core_intern_country_efbe63_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicInstitutionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=200, verbose_name="Nom de l'institution")),
                ('institution_type', models.CharField(choices=[('ministere', 'Ministère'), ('primature', 'Primature'), ('assemblee_nationale', 'Assemblée Nationale'), ('commune', 'Commune'), ('service_urgence', "Service d'urgence"), ('forces_ordre', "Forces de l'ordre"), ('autre', 'Autre institution publique')], max_length=50, verbose_name="Type d'institution")),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département/Service')),
                ('official_registration_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'enregistrement officiel")),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Personne de contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_institution_profile', to='core.userprofile')),
            ],
            options={
                'verbose_name': 'Profil Administration Publique',
                'verbose_name_plural': 'Profils Administrations Publiques',
                'indexes': [models.Index(fields=['institution_type'], name='core_public_institu_524374_idx'), models.Index(fields=['institution_name'], name='core_public_institu_08a2a2_idx')],
            },
        ),
    ]
