# Generated by Django 5.2.7 on 2025-11-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='background_attachment',
            field=models.CharField(choices=[('scroll', 'Scroll'), ('fixed', 'Fixed')], default='scroll', max_length=10, verbose_name='Background Attachment'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/footer_backgrounds/', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='background_opacity',
            field=models.FloatField(default=1.0, help_text='0.0 (transparent) to 1.0 (opaque)', verbose_name='Background Opacity'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='background_overlay_color',
            field=models.CharField(default='rgba(0,0,0,0.5)', help_text='Overlay color over background image (e.g., rgba(0,0,0,0.5))', max_length=20, verbose_name='Overlay Color'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='background_position',
            field=models.CharField(choices=[('center center', 'Center'), ('top center', 'Top Center'), ('bottom center', 'Bottom Center'), ('left center', 'Left Center'), ('right center', 'Right Center'), ('top left', 'Top Left'), ('top right', 'Top Right'), ('bottom left', 'Bottom Left'), ('bottom right', 'Bottom Right')], default='center center', max_length=30, verbose_name='Background Position'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='background_repeat',
            field=models.CharField(choices=[('no-repeat', 'No Repeat'), ('repeat', 'Repeat'), ('repeat-x', 'Repeat Horizontally'), ('repeat-y', 'Repeat Vertically')], default='no-repeat', max_length=20, verbose_name='Background Repeat'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='background_size',
            field=models.CharField(choices=[('cover', 'Cover (fill entire area)'), ('contain', 'Contain (fit within area)'), ('auto', 'Auto (original size)'), ('100% 100%', 'Stretch (100% width and height)')], default='cover', max_length=20, verbose_name='Background Size'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='border_top_color',
            field=models.CharField(default='#dee2e6', max_length=7, verbose_name='Border Top Color'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='border_top_width',
            field=models.IntegerField(default=0, help_text='Border width in pixels (0 for none)', verbose_name='Border Top Width'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='enable_overlay',
            field=models.BooleanField(default=False, verbose_name='Enable Overlay'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='heading_color',
            field=models.CharField(default='#ffffff', help_text='Footer heading color', max_length=7, verbose_name='Heading Color'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='link_color',
            field=models.CharField(default='#adb5bd', help_text='Footer link color', max_length=7, verbose_name='Link Color'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='link_hover_color',
            field=models.CharField(default='#ffffff', help_text='Footer link hover color', max_length=7, verbose_name='Link Hover Color'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='padding_bottom',
            field=models.IntegerField(default=60, help_text='Bottom padding in pixels', verbose_name='Padding Bottom'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='padding_top',
            field=models.IntegerField(default=60, help_text='Top padding in pixels', verbose_name='Padding Top'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='background_opacity',
            field=models.FloatField(default=1.0, help_text='0.0 (transparent) to 1.0 (opaque)', verbose_name='Background Opacity'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='border_bottom_color',
            field=models.CharField(default='#dee2e6', max_length=7, verbose_name='Border Color'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='border_bottom_width',
            field=models.IntegerField(default=0, help_text='Border width in pixels (0 for none)', verbose_name='Border Width'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_background_color',
            field=models.CharField(default='#ffffff', help_text='Button background color', max_length=7, verbose_name='Button Background'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_hover_background',
            field=models.CharField(default='#e3f2fd', help_text='Button hover background', max_length=7, verbose_name='Button Hover Background'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='button_text_color',
            field=models.CharField(default='#1a73e8', help_text='Button text color', max_length=7, verbose_name='Button Text'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='dropdown_background_color',
            field=models.CharField(default='#ffffff', help_text='Dropdown menu background', max_length=7, verbose_name='Dropdown Background'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='dropdown_hover_color',
            field=models.CharField(default='#f8f9fa', help_text='Dropdown item hover background', max_length=7, verbose_name='Dropdown Hover'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='dropdown_text_color',
            field=models.CharField(default='#212529', help_text='Dropdown menu text color', max_length=7, verbose_name='Dropdown Text Color'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='header_padding',
            field=models.IntegerField(default=15, help_text='Padding in pixels', verbose_name='Header Padding'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='link_color',
            field=models.CharField(default='#ffffff', help_text='Menu link color', max_length=7, verbose_name='Link Color'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='link_hover_color',
            field=models.CharField(default='#e3f2fd', help_text='Menu link hover color', max_length=7, verbose_name='Link Hover Color'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='logo_height',
            field=models.IntegerField(default=40, help_text='Logo height in pixels', verbose_name='Logo Height'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='shadow_color',
            field=models.CharField(default='rgba(0,0,0,0.1)', help_text='CSS shadow value', max_length=20, verbose_name='Shadow Color'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='shadow_enabled',
            field=models.BooleanField(default=True, verbose_name='Enable Shadow'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='background_color',
            field=models.CharField(default='#212529', help_text='Footer background color', max_length=7, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Footer text color', max_length=7, verbose_name='Text Color'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='background_color',
            field=models.CharField(default='#1a73e8', help_text='Header background color', max_length=7, verbose_name='Background Color'),
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='text_color',
            field=models.CharField(default='#ffffff', help_text='Text and brand color', max_length=7, verbose_name='Text Color'),
        ),
    ]
