# Generated by Django 5.2.7 on 2025-11-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_footersettings_background_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_style', models.CharField(choices=[('enhanced', 'Enhanced (Modern with backdrop blur)'), ('classic', 'Classic (Standard Bootstrap)'), ('minimal', 'Minimal (Simple design)')], default='enhanced', help_text='Choose the navigation bar style', max_length=20, verbose_name='Navbar Style')),
                ('use_enhanced_navbar', models.BooleanField(default=True, help_text='Enable the enhanced navbar with modern styling and animations', verbose_name='Use Enhanced Navbar')),
                ('navbar_background_opacity', models.DecimalField(decimal_places=2, default=0.95, help_text='Background opacity (0.0 to 1.0)', max_digits=3, verbose_name='Navbar Background Opacity')),
                ('enable_backdrop_blur', models.BooleanField(default=True, help_text='Enable blur effect on navbar background', verbose_name='Enable Backdrop Blur')),
                ('blur_amount', models.IntegerField(default=10, help_text='Blur amount in pixels', verbose_name='Blur Amount')),
                ('enable_scroll_effect', models.BooleanField(default=True, help_text='Change navbar appearance on scroll', verbose_name='Enable Scroll Effect')),
                ('scroll_threshold', models.IntegerField(default=50, help_text='Scroll threshold in pixels for effect activation', verbose_name='Scroll Threshold')),
                ('enable_animations', models.BooleanField(default=True, help_text='Enable smooth animations and transitions', verbose_name='Enable Animations')),
                ('animation_duration', models.DecimalField(decimal_places=2, default=0.3, help_text='Animation duration in seconds', max_digits=3, verbose_name='Animation Duration')),
                ('highlight_active_links', models.BooleanField(default=True, help_text='Automatically highlight the active navigation link', verbose_name='Highlight Active Links')),
                ('active_link_background', models.CharField(default='rgba(var(--bs-primary-rgb), 0.15)', help_text='Background color for active links', max_length=7, verbose_name='Active Link Background')),
                ('mobile_menu_style', models.CharField(choices=[('slide', 'Slide Down'), ('fade', 'Fade In'), ('collapse', 'Collapse')], default='slide', max_length=20, verbose_name='Mobile Menu Style')),
                ('brand_hover_effect', models.BooleanField(default=True, help_text='Enable scale effect on brand hover', verbose_name='Brand Hover Effect')),
                ('link_hover_lift', models.BooleanField(default=True, help_text='Enable lift effect on link hover', verbose_name='Link Hover Lift')),
                ('link_hover_scale', models.BooleanField(default=False, help_text='Enable scale effect on link hover', verbose_name='Link Hover Scale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
