# Generated by Django 5.2.7 on 2025-11-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_theme_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='active_link_background',
            field=models.CharField(default='rgba(var(--bs-primary-rgb), 0.15)', help_text='Background color for active links (CSS color value)', max_length=50, verbose_name='Active Link Background'),
        ),
    ]
