# Generated by Django 5.2.7 on 2025-11-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_fix_theme_settings_active_link_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='theme_name',
            field=models.CharField(choices=[('default', 'Default (Blue)'), ('green_theme', 'Green Theme (Teal/Green)'), ('purple_theme', 'Purple Theme'), ('red_theme', 'Red Theme'), ('custom', 'Custom')], default='default', help_text='Choose a predefined theme or custom', max_length=30, verbose_name='Theme Name'),
        ),
    ]
