# Generated by Django 5.2.7 on 2025-11-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_add_theme_colors_and_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesettings',
            name='accent_color',
            field=models.CharField(default='#20C997', help_text='Accent color for buttons and highlights (hex code)', max_length=7, verbose_name='Accent Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='button_background_color',
            field=models.CharField(default='#20C997', help_text='Button background color (hex code)', max_length=7, verbose_name='Button Background Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='button_text_color',
            field=models.CharField(default='#FFFFFF', help_text='Button text color (hex code)', max_length=7, verbose_name='Button Text Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_link_color',
            field=models.CharField(default='#6C757D', help_text='Navbar link color (hex code)', max_length=7, verbose_name='Navbar Link Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_link_hover_color',
            field=models.CharField(default='#20C997', help_text='Navbar link hover color (hex code)', max_length=7, verbose_name='Navbar Link Hover Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='navbar_text_color',
            field=models.CharField(default='#343A40', help_text='Navbar text color (hex code)', max_length=7, verbose_name='Navbar Text Color'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='primary_color',
            field=models.CharField(default='#1a73e8', help_text='Primary theme color (hex code)', max_length=7, verbose_name='Primary Color'),
        ),
    ]
