# Generated by Django 5.2.7 on 2025-11-24 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, help_text="Unique API key token", max_length=64, unique=True)),
                ("name", models.CharField(help_text="Descriptive name for the API key", max_length=255)),
                ("organization", models.CharField(help_text="Organization name", max_length=255)),
                ("contact_email", models.EmailField(help_text="Contact email for the API key owner", max_length=254)),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, help_text="Whether the API key is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="Expiration date for the API key", null=True),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, help_text="Last time this API key was used", null=True),
                ),
                ("rate_limit_per_hour", models.IntegerField(default=1000, help_text="Maximum requests per hour")),
                ("rate_limit_per_day", models.IntegerField(default=10000, help_text="Maximum requests per day")),
                ("description", models.TextField(blank=True, help_text="Detailed description of the API key purpose")),
                (
                    "ip_whitelist",
                    models.JSONField(
                        blank=True, default=list, help_text="List of allowed IP addresses (empty = all IPs allowed)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this API key",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKeyEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("REVOKED", "Revoked"),
                            ("RENEWED", "Renewed"),
                            ("PERMISSIONS_CHANGED", "Permissions Changed"),
                            ("RATE_LIMIT_CHANGED", "Rate Limit Changed"),
                        ],
                        help_text="Type of event",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("details", models.JSONField(default=dict, help_text="Additional event details")),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="api.apikey"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key Event",
                "verbose_name_plural": "API Key Events",
                "db_table": "api_key_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="APIKeyPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "resource",
                    models.CharField(
                        choices=[
                            ("vehicles", "Vehicles"),
                            ("payments", "Payments"),
                            ("users", "Users"),
                            ("documents", "Documents"),
                            ("qrcodes", "QR Codes"),
                            ("notifications", "Notifications"),
                            ("contraventions", "Contraventions"),
                            ("*", "All Resources"),
                        ],
                        help_text="Resource type",
                        max_length=100,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("read", "Read Only"), ("write", "Read & Write"), ("admin", "Full Admin")],
                        help_text="Permission scope",
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="permissions", to="api.apikey"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        help_text="User who granted this permission",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key Permission",
                "verbose_name_plural": "API Key Permissions",
                "db_table": "api_key_permissions",
                "unique_together": {("api_key", "resource")},
            },
        ),
    ]
