# Generated by Django 5.2.7 on 2025-11-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(db_index=True, help_text="Unique API key token", max_length=128, unique=True),
        ),
    ]
