# Generated by Django 5.2.7 on 2025-11-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_audit_logging"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apiauditlog",
            new_name="api_audit_l_timesta_63a051_idx",
            old_name="api_audit_timestam_idx",
        ),
        migrations.RenameIndex(
            model_name="apiauditlog",
            new_name="api_audit_l_correla_6f8153_idx",
            old_name="api_audit_corr_id_idx",
        ),
        migrations.RenameIndex(
            model_name="apiauditlog",
            new_name="api_audit_l_endpoin_7570fb_idx",
            old_name="api_audit_endpoint_idx",
        ),
        migrations.RenameIndex(
            model_name="apiauditlog",
            new_name="api_audit_l_status__ba3863_idx",
            old_name="api_audit_status_idx",
        ),
        migrations.RenameIndex(
            model_name="datachangelog",
            new_name="data_change_timesta_ac106c_idx",
            old_name="data_change_timestam_idx",
        ),
        migrations.RenameIndex(
            model_name="datachangelog",
            new_name="data_change_correla_58a965_idx",
            old_name="data_change_corr_id_idx",
        ),
        migrations.RenameIndex(
            model_name="datachangelog",
            new_name="data_change_operati_80074b_idx",
            old_name="data_change_operation_idx",
        ),
        migrations.RenameIndex(
            model_name="datachangelog",
            new_name="data_change_content_db5dc6_idx",
            old_name="data_change_contenttype_idx",
        ),
    ]
