# Generated by Django 5.2.7 on 2025-11-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_api_audit_timestam_idx_api_audit_l_timesta_63a051_idx_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("target_url", models.URLField(max_length=500, help_text="Endpoint to POST webhook events")),
                ("is_active", models.BooleanField(default=True, db_index=True)),
                ("event_types", models.JSONField(default=list, blank=True, help_text="List of event types subscribed")),
                ("secret", models.CharField(max_length=128, help_text="Shared secret for HMAC-SHA256 signature")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "webhook_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhooksubscription",
            index=models.Index(fields=["is_active"], name="webhook_sub_is_act_idx"),
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ("event_type", models.CharField(max_length=100, db_index=True)),
                ("payload", models.JSONField(default=dict)),
                ("signature", models.CharField(max_length=128, blank=True)),
                ("status", models.CharField(max_length=20, choices=[("pending", "Pending"), ("success", "Success"), ("failed", "Failed")], default="pending", db_index=True)),
                ("attempt_count", models.IntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(null=True, blank=True)),
                ("response_code", models.IntegerField(null=True, blank=True)),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="api.webhooksubscription"),
                ),
            ],
            options={
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["status"], name="webhook_del_status_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["event_type"], name="webhook_del_event_type_idx"),
        ),
    ]

