# Generated by Django 5.2.7 on 2025-11-26 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_api_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataAccessLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "access_type",
                    models.CharField(
                        choices=[("read", "Read"), ("export", "Export"), ("modify", "Modify"), ("delete", "Delete")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(help_text="Type of data accessed (profile, vehicle, payment)", max_length=100),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("consent_verified", models.BooleanField(default=False)),
                ("consent_type", models.CharField(blank=True, max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Data Access Log",
                "verbose_name_plural": "Data Access Logs",
                "db_table": "api_data_access_log",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="DataConsent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("profile_access", "Profile Data Access"),
                            ("vehicle_data", "Vehicle Data Access"),
                            ("payment_history", "Payment History Access"),
                            ("location_tracking", "Location Tracking"),
                            ("marketing", "Marketing Communications"),
                            ("data_sharing", "Data Sharing with Third Parties"),
                            ("api_access", "API Data Access"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("granted", "Granted"), ("revoked", "Revoked"), ("expired", "Expired")],
                        db_index=True,
                        default="granted",
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField(help_text="Purpose of data processing")),
                ("granted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, help_text="Optional expiration date", null=True)),
                (
                    "granted_via",
                    models.CharField(help_text="How consent was granted (web, api, mobile)", max_length=100),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Data Consent",
                "verbose_name_plural": "Data Consents",
                "db_table": "api_data_consent",
                "ordering": ["-granted_at"],
            },
        ),
        migrations.CreateModel(
            name="DataDeletionRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("requested_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "data_types",
                    models.JSONField(
                        default=list, help_text="List of data types to delete: ['profile', 'vehicles', 'payments']"
                    ),
                ),
                ("deletion_report", models.JSONField(blank=True, default=dict)),
                ("rejection_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Data Deletion Request",
                "verbose_name_plural": "Data Deletion Requests",
                "db_table": "api_data_deletion_request",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_type", models.CharField(db_index=True, max_length=100, unique=True)),
                ("retention_days", models.IntegerField(help_text="Number of days to retain data")),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("legal_basis", models.TextField(help_text="Legal justification for retention period")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Retention Policy",
                "verbose_name_plural": "Data Retention Policies",
                "db_table": "api_data_retention_policy",
                "ordering": ["data_type"],
            },
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhook_del_status_269a2c_idx",
            old_name="webhook_del_status_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhook_del_event_t_d86659_idx",
            old_name="webhook_del_event_type_idx",
        ),
        migrations.RenameIndex(
            model_name="webhooksubscription",
            new_name="webhook_sub_is_acti_76d62e_idx",
            old_name="webhook_sub_is_act_idx",
        ),
        migrations.AlterField(
            model_name="apiversion",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="webhookdelivery",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="webhooksubscription",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="dataaccesslog",
            name="accessed_by",
            field=models.ForeignKey(
                help_text="User or system that accessed the data",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_accesses_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataaccesslog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_access_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataconsent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="data_consents", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="datadeletionrequest",
            name="processed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deletion_requests_processed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datadeletionrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deletion_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(fields=["user", "accessed_at"], name="api_data_ac_user_id_a074c6_idx"),
        ),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(fields=["accessed_by", "accessed_at"], name="api_data_ac_accesse_5fd9d5_idx"),
        ),
        migrations.AddIndex(
            model_name="dataaccesslog",
            index=models.Index(fields=["access_type", "data_type"], name="api_data_ac_access__dd11db_idx"),
        ),
        migrations.AddIndex(
            model_name="dataconsent",
            index=models.Index(fields=["user", "consent_type", "status"], name="api_data_co_user_id_04ce0e_idx"),
        ),
        migrations.AddIndex(
            model_name="dataconsent",
            index=models.Index(fields=["status", "expires_at"], name="api_data_co_status_2890d3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dataconsent",
            unique_together={("user", "consent_type")},
        ),
        migrations.AddIndex(
            model_name="datadeletionrequest",
            index=models.Index(fields=["user", "status"], name="api_data_de_user_id_e12a2a_idx"),
        ),
        migrations.AddIndex(
            model_name="datadeletionrequest",
            index=models.Index(fields=["status", "requested_at"], name="api_data_de_status_410315_idx"),
        ),
    ]
