# Generated by Django 5.2.7 on 2025-11-01 02:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puissance_min_cv', models.PositiveIntegerField(verbose_name='Puissance min (CV)')),
                ('puissance_max_cv', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance max (CV)')),
                ('source_energie', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Electrique', 'Électrique'), ('Hybride', 'Hybride')], max_length=20, verbose_name="Source d'énergie")),
                ('age_min_annees', models.PositiveIntegerField(default=0, verbose_name='Âge minimum (années)')),
                ('age_max_annees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge maximum (années)')),
                ('montant_ariary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant (Ariary)')),
                ('annee_fiscale', models.PositiveIntegerField(verbose_name='Année fiscale')),
                ('est_active', models.BooleanField(default=True, verbose_name='Est active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grilles tarifaires',
                'indexes': [models.Index(fields=['annee_fiscale', 'est_active'], name='vehicles_gr_annee_f_2aced1_idx'), models.Index(fields=['puissance_min_cv', 'puissance_max_cv', 'source_energie'], name='vehicles_gr_puissan_e47476_idx')],
                'unique_together': {('puissance_min_cv', 'puissance_max_cv', 'source_energie', 'age_min_annees', 'age_max_annees', 'annee_fiscale')},
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('plaque_immatriculation', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]{1,4}\\s[A-Z]{2,3}$', 'Format: 1234 TAA')])),
                ('puissance_fiscale_cv', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Puissance fiscale (CV)')),
                ('cylindree_cm3', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cylindrée (cm³)')),
                ('source_energie', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Electrique', 'Électrique'), ('Hybride', 'Hybride')], max_length=20, verbose_name="Source d'énergie")),
                ('date_premiere_circulation', models.DateField(verbose_name='Date de première circulation')),
                ('categorie_vehicule', models.CharField(choices=[('Personnel', 'Personnel'), ('Commercial', 'Commercial'), ('Ambulance', 'Ambulance'), ('Sapeurs-pompiers', 'Sapeurs-pompiers'), ('Administratif', 'Administratif'), ('Convention_internationale', 'Convention internationale')], default='Personnel', max_length=50, verbose_name='Catégorie de véhicule')),
                ('type_vehicule', models.CharField(choices=[('Terrestre', 'Terrestre'), ('Ferroviaire', 'Ferroviaire'), ('Maritime', 'Maritime'), ('Aerien', 'Aérien')], default='Terrestre', max_length=30, verbose_name='Type de véhicule')),
                ('specifications_techniques', models.JSONField(blank=True, default=dict, verbose_name='Spécifications techniques')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'indexes': [models.Index(fields=['proprietaire'], name='vehicles_ve_proprie_0798fa_idx'), models.Index(fields=['categorie_vehicule'], name='vehicles_ve_categor_0f5990_idx'), models.Index(fields=['type_vehicule'], name='vehicles_ve_type_ve_d16de7_idx'), models.Index(fields=['source_energie'], name='vehicles_ve_source__0e6e46_idx'), models.Index(fields=['puissance_fiscale_cv'], name='vehicles_ve_puissan_fe358b_idx')],
            },
        ),
    ]
