# Generated by Django 5.2.7 on 2025-11-01 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='cylindree_cm3',
            field=models.PositiveIntegerField(default=1000, help_text='Ex: 110 pour un scooter, 1900 pour une voiture', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cylindrée (en Cm3 ou cc)'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='puissance_fiscale_cv',
            field=models.PositiveIntegerField(help_text='Trouvez cette information sur votre carte grise. Elle est utilisée pour le calcul de la taxe.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Puissance Fiscale (en CV)'),
        ),
    ]
