# Generated by Django 5.2.7 on 2025-11-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicule_cylindree_cm3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('Voiture', 'Voiture'), ('Moto', 'Moto'), ('Scooter', 'Scooter'), ('Camionnette', 'Camionnette'), ('Camion', 'Camion'), ('Bus', 'Bus'), ('Autre', 'Autre')], default='Voiture', help_text='Type spécifique du véhicule (Voiture, Moto, Scooter, etc.)', max_length=30, verbose_name='Type de véhicule'),
        ),
    ]
