# Generated by Django 5.2.7 on 2025-11-02 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_update_vehicle_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Voiture, Moto, Scooter, Camionnette, etc.', max_length=50, unique=True, verbose_name='Nom du type de véhicule')),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du type de véhicule', verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, help_text='Décochez pour désactiver ce type de véhicule', verbose_name='Est actif')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans les listes (0 = premier)", verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de véhicule',
                'verbose_name_plural': 'Types de véhicules',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.RenameIndex(
            model_name='vehicule',
            new_name='vehicles_ve_type_ve_80f00e_idx',
            old_name='vehicles_ve_type_ve_d16de7_idx',
        ),
        migrations.AddIndex(
            model_name='vehicletype',
            index=models.Index(fields=['est_actif'], name='vehicles_ve_est_act_869b75_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletype',
            index=models.Index(fields=['ordre_affichage'], name='vehicles_ve_ordre_a_e4a324_idx'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.ForeignKey(help_text='Type spécifique du véhicule (Voiture, Moto, Scooter, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='vehicules', to='vehicles.vehicletype', verbose_name='Type de véhicule'),
        ),
    ]
