# Generated by Django 5.2.7 on 2025-11-02 13:58

from django.db import migrations


def populate_vehicle_types(apps, schema_editor):
    """Populate VehicleType table with existing vehicle types"""
    VehicleType = apps.get_model('vehicles', 'VehicleType')
    
    # Original vehicle types from the old choices
    vehicle_types = [
        ('Voiture', 'Véhicule de tourisme personnel', 1),
        ('Moto', 'Motocyclette', 2),
        ('Scooter', 'Scooter ou cyclomoteur', 3),
        ('Camionnette', 'Véhicule utilitaire léger', 4),
        ('Camion', 'Véhicule de transport de marchandises', 5),
        ('Bus', 'Véhicule de transport de passagers', 6),
        ('Autre', 'Autre type de véhicule', 7),
    ]
    
    for nom, description, ordre in vehicle_types:
        VehicleType.objects.get_or_create(
            nom=nom,
            defaults={
                'description': description,
                'est_actif': True,
                'ordre_affichage': ordre
            }
        )


def update_existing_vehicles(apps, schema_editor):
    """Update existing Vehicule records to use VehicleType ForeignKey"""
    Vehicule = apps.get_model('vehicles', 'Vehicule')
    VehicleType = apps.get_model('vehicles', 'VehicleType')
    
    # Create a mapping from old string values to VehicleType objects
    type_mapping = {}
    for vtype in VehicleType.objects.all():
        type_mapping[vtype.nom] = vtype
    
    # Update all existing vehicles
    for vehicule in Vehicule.objects.all():
        old_type = vehicule.type_vehicule
        if isinstance(old_type, str) and old_type in type_mapping:
            vehicule.type_vehicule = type_mapping[old_type]
            vehicule.save()


def reverse_populate_vehicle_types(apps, schema_editor):
    """Reverse migration - convert ForeignKey back to CharField"""
    # This would be complex to implement properly, so we'll just pass
    # In a real scenario, you might want to implement this
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicletype_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_vehicle_types,
            reverse_populate_vehicle_types
        ),
        migrations.RunPython(
            update_existing_vehicles,
            reverse_populate_vehicle_types
        ),
    ]
