# Generated by Django 5.2.7 on 2025-11-04 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20251102_1658'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('carte_grise', 'Carte grise'), ('assurance', 'Assurance'), ('controle_technique', 'Contrôle technique'), ('photo_plaque', 'Photo de la plaque'), ('autre', 'Autre document')], max_length=50)),
                ('fichier', models.FileField(upload_to='vehicle_documents/%Y/%m/%d')),
                ('note', models.TextField(blank=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('soumis', 'Soumis'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], default='soumis', max_length=20)),
                ('verification_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_documents', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicule')),
            ],
            options={
                'verbose_name': 'Document du véhicule',
                'verbose_name_plural': 'Documents du véhicule',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicule'], name='vehicles_do_vehicul_1d12d6_idx'), models.Index(fields=['document_type'], name='vehicles_do_documen_f27503_idx'), models.Index(fields=['verification_status'], name='vehicles_do_verific_8b169b_idx')],
            },
        ),
    ]
