# Generated by Django 5.2.7 on 2025-11-07 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_documentvehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='a_plaque_immatriculation',
            field=models.BooleanField(default=True, help_text='Décochez pour les motos ou véhicules sans plaque officielle', verbose_name="Possède une plaque d'immatriculation"),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='plaque_immatriculation',
            field=models.CharField(help_text='Format: 1234 TAA. Pour les véhicules sans plaque, utilisez TEMP-XXXXXXXX', max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^([0-9]{1,4}\\s[A-Z]{2,3}|TEMP-[A-Z0-9]{8})$', 'Format: 1234 TAA ou TEMP-XXXXXXXX pour véhicules sans plaque')], verbose_name="Plaque d'immatriculation ou Identifiant"),
        ),
    ]
