# Generated by Django 5.2.7 on 2025-11-07 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_add_temp_plate_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='nom_proprietaire',
            field=models.CharField(blank=True, default='', help_text='Nom complet du propriétaire légal du véhicule', max_length=200, verbose_name='Nom du propriétaire'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='plaque_immatriculation',
            field=models.CharField(help_text='Format: 1234TAA (sans espace). Pour les véhicules sans plaque, utilisez TEMP-XXXXXXXX', max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^([0-9]{1,4}[A-Z]{2,3}|TEMP-[A-Z0-9]{8})$', 'Format: 1234TAA (sans espace) ou TEMP-XXXXXXXX pour véhicules sans plaque')], verbose_name="Plaque d'immatriculation ou Identifiant"),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='proprietaire',
            field=models.ForeignKey(help_text="L'utilisateur qui gère ce véhicule dans le système", on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur gestionnaire'),
        ),
    ]
