# Generated by Django 5.2.7 on 2025-11-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicule_nom_proprietaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='couleur',
            field=models.CharField(blank=True, help_text='Couleur principale du véhicule', max_length=50, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(default='', help_text='Marque du véhicule (ex: TOYOTA, HONDA, YAMAHA)', max_length=100, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(blank=True, help_text='Modèle du véhicule (ex: COROLLA, CIVIC, YZF)', max_length=100, verbose_name='Modèle'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number (Numéro de châssis)', max_length=50, verbose_name='VIN'),
        ),
    ]
