# Generated by Django 5.2.7 on 2025-11-21 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_vehicule_couleur_vehicule_marque_vehicule_modele_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEditOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champs_modifies', models.JSONField(default=dict)),
                ('selection', models.JSONField(default=list)),
                ('statut', models.CharField(choices=[('PENDING', 'PENDING'), ('APPLIED', 'APPLIED'), ('ROLLED_BACK', 'ROLLED_BACK')], default='PENDING', max_length=16)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('applique_le', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkEditChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avant', models.JSONField(default=dict)),
                ('apres', models.JSONField(default=dict)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicule')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changements', to='vehicles.bulkeditoperation')),
            ],
        ),
        migrations.CreateModel(
            name='FleetImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(max_length=16)),
                ('mapping_colonnes', models.JSONField(default=dict)),
                ('options', models.JSONField(default=dict)),
                ('statut', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('ROLLED_BACK', 'ROLLED_BACK')], default='PENDING', max_length=16)),
                ('total_lignes', models.PositiveIntegerField(default=0)),
                ('reussites', models.PositiveIntegerField(default=0)),
                ('echecs', models.PositiveIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('resume_erreurs', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FleetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=64)),
                ('donnees_action', models.JSONField(default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agent_utilisateur', models.CharField(blank=True, max_length=255)),
                ('previous_hash', models.CharField(blank=True, max_length=128)),
                ('current_hash', models.CharField(blank=True, max_length=128)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('operation_modification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.bulkeditoperation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicule')),
                ('lot_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.fleetimportbatch')),
            ],
        ),
        migrations.CreateModel(
            name='FleetImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.PositiveIntegerField()),
                ('donnees', models.JSONField(default=dict)),
                ('erreurs', models.JSONField(default=list)),
                ('statut', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('ERROR', 'ERROR'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=16)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='vehicles.fleetimportbatch')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicule')),
            ],
        ),
    ]
