# Generated by Django 5.2.7 on 2025-11-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_add_aerial_and_maritime_vehicle_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grilletarifaire',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='documentvehicule',
            name='document_type',
            field=models.CharField(choices=[('carte_grise', 'Carte grise'), ('assurance', 'Assurance'), ('controle_technique', 'Contrôle technique'), ('photo_plaque', 'Photo de la plaque'), ('certificat_navigabilite', 'Certificat de navigabilité'), ('certificat_immatriculation_aerienne', "Certificat d'immatriculation aérienne"), ('assurance_aerienne', 'Assurance aérienne'), ('carnet_vol', 'Carnet de vol'), ('certificat_francisation', 'Certificat de francisation'), ('permis_navigation', 'Permis de navigation'), ('assurance_maritime', 'Assurance maritime'), ('certificat_jaugeage', 'Certificat de jaugeage'), ('autre', 'Autre document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='grilletarifaire',
            name='age_min_annees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Âge minimum (années)'),
        ),
        migrations.AlterField(
            model_name='grilletarifaire',
            name='puissance_min_cv',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance min (CV)'),
        ),
        migrations.AlterField(
            model_name='grilletarifaire',
            name='source_energie',
            field=models.CharField(blank=True, choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Electrique', 'Électrique'), ('Hybride', 'Hybride')], max_length=20, null=True, verbose_name="Source d'énergie"),
        ),
    ]
