# Generated by Django 5.2.7 on 2025-11-23 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_create_maritime_tariff_grids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='statut_declaration',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée')], default='BROUILLON', help_text="État d'avancement de la déclaration fiscale", max_length=20, verbose_name='Statut de la déclaration'),
        ),
        migrations.AddIndex(
            model_name='vehicule',
            index=models.Index(fields=['statut_declaration'], name='idx_statut_declaration'),
        ),
    ]
