# Generated by Django 5.2.7 on 2025-11-13 03:30

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contravention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pv', models.CharField(help_text='Format: PV-YYYYMMDD-XXXXXX', max_length=50, unique=True, verbose_name='Numéro PV')),
                ('montant_amende_ariary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Montant de l'amende (Ariary)")),
                ('statut', models.CharField(choices=[('IMPAYEE', 'Impayée'), ('PAYEE', 'Payée'), ('CONTESTEE', 'Contestée'), ('ANNULEE', 'Annulée')], default='IMPAYEE', max_length=20, verbose_name='Statut')),
                ('date_limite_paiement', models.DateField(verbose_name='Date limite de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contravention',
                'verbose_name_plural': 'Contraventions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['numero_pv'], name='contraventi_numero__a361e9_idx'), models.Index(fields=['statut'], name='contraventi_statut_d9e65c_idx'), models.Index(fields=['date_limite_paiement'], name='contraventi_date_li_348eee_idx')],
            },
        ),
    ]
