# Generated by Django 5.2.7 on 2025-11-13 03:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contraventions', '0001_modify_paiementtaxe_for_contraventions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSysteme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delai_paiement_standard_jours', models.IntegerField(default=15, help_text='Nombre de jours pour payer une contravention standard', verbose_name='Délai de paiement standard (jours)')),
                ('delai_paiement_immediat_jours', models.IntegerField(default=1, help_text='Nombre de jours pour paiement immédiat sur place', verbose_name='Délai de paiement immédiat (jours)')),
                ('penalite_retard_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Pourcentage de majoration en cas de retard de paiement', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pénalité de retard (%)')),
                ('frais_transport_fourriere_ariary', models.DecimalField(decimal_places=2, default=Decimal('20000.00'), help_text='Frais de transport vers la fourrière', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais de transport fourrière (Ariary)')),
                ('frais_gardiennage_journalier_ariary', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Frais de gardiennage par jour en fourrière', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais de gardiennage journalier (Ariary)')),
                ('duree_minimale_fourriere_jours', models.IntegerField(default=10, help_text='Durée minimale de mise en fourrière', verbose_name='Durée minimale fourrière (jours)')),
                ('duree_minimale_fourriere_perissable_jours', models.IntegerField(default=5, help_text='Durée minimale pour véhicules transportant des denrées périssables', verbose_name='Durée minimale fourrière périssable (jours)')),
                ('delai_annulation_directe_heures', models.IntegerField(default=24, help_text="Délai pendant lequel l'agent peut annuler directement", verbose_name="Délai d'annulation directe (heures)")),
                ('delai_contestation_jours', models.IntegerField(default=30, help_text='Nombre de jours pour contester une contravention', verbose_name='Délai de contestation (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du système',
                'verbose_name_plural': 'Configuration du système',
            },
        ),
    ]
