# Generated by Django 5.2.7 on 2025-11-13 03:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contraventions', '0002_add_configuration_systeme'),
        ('payments', '0008_modify_paiementtaxe_for_contraventions'),
        ('vehicles', '0009_vehicule_couleur_vehicule_marque_vehicule_modele_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentControleurProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(help_text="Matricule unique de l'agent", max_length=50, unique=True, verbose_name='Matricule')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('unite_affectation', models.CharField(help_text="Unité ou brigade d'affectation", max_length=200, verbose_name="Unité d'affectation")),
                ('grade', models.CharField(max_length=100, verbose_name='Grade')),
                ('autorite_type', models.CharField(choices=[('POLICE_NATIONALE', 'Police Nationale'), ('GENDARMERIE', 'Gendarmerie'), ('POLICE_COMMUNALE', 'Police Communale')], max_length=50, verbose_name="Type d'autorité")),
                ('juridiction', models.CharField(help_text='Zone de compétence géographique', max_length=200, verbose_name='Juridiction')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil Agent Contrôleur',
                'verbose_name_plural': 'Profils Agents Contrôleurs',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cin', models.CharField(help_text="Numéro de Carte d'Identité Nationale (12 chiffres)", max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Le CIN doit contenir exactement 12 chiffres')], verbose_name='Numéro CIN')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('numero_permis', models.CharField(blank=True, max_length=50, verbose_name='Numéro de permis de conduire')),
                ('categorie_permis', models.CharField(blank=True, help_text='Ex: A, B, C, D, E', max_length=20, verbose_name='Catégorie de permis')),
                ('date_delivrance_permis', models.DateField(blank=True, null=True, verbose_name='Date de délivrance du permis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conducteur',
                'verbose_name_plural': 'Conducteurs',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Contestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_contestation', models.CharField(max_length=50, unique=True, verbose_name='Numéro de contestation')),
                ('nom_demandeur', models.CharField(max_length=200, verbose_name='Nom du demandeur')),
                ('email_demandeur', models.EmailField(blank=True, max_length=254, verbose_name='Email du demandeur')),
                ('telephone_demandeur', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du demandeur')),
                ('motif', models.TextField(verbose_name='Motif de la contestation')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_EXAMEN', 'En examen'), ('ACCEPTEE', 'Acceptée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_examen', models.DateTimeField(blank=True, null=True, verbose_name="Date d'examen")),
                ('decision_motif', models.TextField(blank=True, verbose_name='Motif de la décision')),
                ('documents_justificatifs', models.JSONField(blank=True, default=list, help_text='URLs des documents', verbose_name='Documents justificatifs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contestation',
                'verbose_name_plural': 'Contestations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContraventionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('PAYMENT', 'Paiement'), ('CANCEL', 'Annulation'), ('CONTEST', 'Contestation'), ('FOURRIERE', 'Mise en fourrière'), ('RESTITUTION', 'Restitution')], max_length=50, verbose_name="Type d'action")),
                ('action_data', models.JSONField(blank=True, default=dict, verbose_name="Données de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('previous_hash', models.CharField(blank=True, help_text='Pour chaînage cryptographique', max_length=64, verbose_name='Hash précédent')),
                ('current_hash', models.CharField(blank=True, max_length=64, verbose_name='Hash actuel')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': "Log d'audit de contravention",
                'verbose_name_plural': "Logs d'audit de contraventions",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DossierFourriere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_dossier', models.CharField(help_text='Format: FOUR-YYYYMMDD-XXXXX', max_length=50, unique=True, verbose_name='Numéro de dossier')),
                ('date_mise_fourriere', models.DateTimeField(verbose_name='Date de mise en fourrière')),
                ('lieu_fourriere', models.CharField(max_length=200, verbose_name='Lieu de la fourrière')),
                ('adresse_fourriere', models.TextField(verbose_name='Adresse de la fourrière')),
                ('type_vehicule', models.CharField(help_text='Pour calcul des frais', max_length=50, verbose_name='Type de véhicule')),
                ('frais_transport_ariary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais de transport (Ariary)')),
                ('frais_gardiennage_journalier_ariary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais de gardiennage journalier (Ariary)')),
                ('duree_minimale_jours', models.IntegerField(default=10, verbose_name='Durée minimale (jours)')),
                ('date_sortie_fourriere', models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie')),
                ('frais_totaux_ariary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Frais totaux (Ariary)')),
                ('statut', models.CharField(choices=[('EN_FOURRIERE', 'En fourrière'), ('RESTITUE', 'Restitué'), ('VENDU_AUX_ENCHERES', 'Vendu aux enchères')], default='EN_FOURRIERE', max_length=20, verbose_name='Statut')),
                ('bon_sortie_numero', models.CharField(blank=True, max_length=50, verbose_name='Numéro de bon de sortie')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dossier de fourrière',
                'verbose_name_plural': 'Dossiers de fourrière',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoContravention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.ImageField(upload_to='contraventions/%Y/%m/%d/', verbose_name='Fichier photo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('metadata_exif', models.JSONField(blank=True, default=dict, help_text='Date, GPS, etc.', verbose_name='Métadonnées EXIF')),
                ('hash_fichier', models.CharField(blank=True, help_text="Pour vérification d'intégrité", max_length=64, verbose_name='Hash SHA-256')),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Marqueurs et textes', verbose_name='Annotations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo de contravention',
                'verbose_name_plural': 'Photos de contraventions',
                'ordering': ['contravention', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='TypeInfraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(help_text="Nom descriptif de l'infraction", max_length=255, verbose_name="Nom de l'infraction")),
                ('article_code', models.CharField(help_text='Article du Code de la Route (ex: L7.1-1)', max_length=50, verbose_name='Article du Code')),
                ('loi_reference', models.CharField(default='Loi n°2017-002 du 6 juillet 2017', max_length=100, verbose_name='Référence légale')),
                ('categorie', models.CharField(choices=[('DELIT_GRAVE', 'Délits routiers graves'), ('CIRCULATION', 'Infractions de circulation'), ('DOCUMENTAIRE', 'Infractions documentaires'), ('SECURITE', 'Infractions de sécurité')], max_length=50, verbose_name='Catégorie')),
                ('montant_min_ariary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant minimum (Ariary)')),
                ('montant_max_ariary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant maximum (Ariary)')),
                ('montant_variable', models.BooleanField(default=False, help_text="Si le montant est déterminé par l'autorité compétente", verbose_name='Montant variable')),
                ('sanctions_administratives', models.TextField(blank=True, help_text='Description des sanctions complémentaires', verbose_name='Sanctions administratives')),
                ('fourriere_obligatoire', models.BooleanField(default=False, verbose_name='Fourrière obligatoire')),
                ('emprisonnement_possible', models.CharField(blank=True, help_text="Durée possible d'emprisonnement", max_length=100, verbose_name='Emprisonnement possible')),
                ('penalite_accident_ariary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Pénalité en cas d'accident (Ariary)")),
                ('penalite_recidive_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pénalité de récidive (%)')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Type d'infraction",
                'verbose_name_plural': "Types d'infractions",
                'ordering': ['categorie', 'nom'],
            },
        ),
        migrations.RemoveIndex(
            model_name='contravention',
            name='contraventi_statut_d9e65c_idx',
        ),
        migrations.RemoveIndex(
            model_name='contravention',
            name='contraventi_date_li_348eee_idx',
        ),
        migrations.AddField(
            model_name='contravention',
            name='a_accident_associe',
            field=models.BooleanField(default=False, verbose_name='Accident associé'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='coordonnees_gps_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='coordonnees_gps_lon',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='date_heure_infraction',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date et heure de l'infraction"),
        ),
        migrations.AddField(
            model_name='contravention',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='delai_paiement_jours',
            field=models.IntegerField(default=15, verbose_name='Délai de paiement (jours)'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='est_recidive',
            field=models.BooleanField(default=False, verbose_name='Est une récidive'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='lieu_infraction',
            field=models.TextField(blank=True, default='', help_text='Adresse textuelle du lieu', verbose_name="Lieu de l'infraction"),
        ),
        migrations.AddField(
            model_name='contravention',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraventions', to='payments.qrcode', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='route_numero',
            field=models.CharField(blank=True, help_text='Ex: RN1, RN7', max_length=20, verbose_name='Numéro de route'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='route_type',
            field=models.CharField(blank=True, choices=[('NATIONALE', 'Route Nationale'), ('COMMUNALE', 'Route Communale'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type de route'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='signature_electronique_conducteur',
            field=models.TextField(blank=True, help_text='Signature en base64', verbose_name='Signature électronique'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='vehicule',
            field=models.ForeignKey(blank=True, help_text='Véhicule enregistré dans le système (si trouvé)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contraventions', to='vehicles.vehicule', verbose_name='Véhicule'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='vehicule_marque_manuelle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marque manuelle'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='vehicule_modele_manuelle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modèle manuel'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='vehicule_plaque_manuelle',
            field=models.CharField(blank=True, help_text='Plaque si véhicule non trouvé dans le système', max_length=20, verbose_name='Plaque manuelle'),
        ),
        migrations.AddField(
            model_name='agentcontroleurprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_controleur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='agent_controleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contraventions', to='contraventions.agentcontroleurprofile', verbose_name='Agent contrôleur'),
        ),
        migrations.AddIndex(
            model_name='conducteur',
            index=models.Index(fields=['cin'], name='contraventi_cin_538d80_idx'),
        ),
        migrations.AddIndex(
            model_name='conducteur',
            index=models.Index(fields=['numero_permis'], name='contraventi_numero__0a8f6a_idx'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contraventions', to='contraventions.conducteur', verbose_name='Conducteur'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='contravention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestations', to='contraventions.contravention', verbose_name='Contravention'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='demandeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestations_soumises', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur (utilisateur)'),
        ),
        migrations.AddField(
            model_name='contestation',
            name='examine_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contestations_examinees', to=settings.AUTH_USER_MODEL, verbose_name='Examiné par'),
        ),
        migrations.AddField(
            model_name='contraventionauditlog',
            name='contravention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='contraventions.contravention', verbose_name='Contravention'),
        ),
        migrations.AddField(
            model_name='contraventionauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='dossierfourriere',
            name='contravention',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_fourriere', to='contraventions.contravention', verbose_name='Contravention'),
        ),
        migrations.AddField(
            model_name='photocontravention',
            name='contravention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='contraventions.contravention', verbose_name='Contravention'),
        ),
        migrations.AddField(
            model_name='photocontravention',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Téléchargé par'),
        ),
        migrations.AddIndex(
            model_name='typeinfraction',
            index=models.Index(fields=['categorie'], name='contraventi_categor_4f96b7_idx'),
        ),
        migrations.AddIndex(
            model_name='typeinfraction',
            index=models.Index(fields=['article_code'], name='contraventi_article_176ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='typeinfraction',
            index=models.Index(fields=['est_actif'], name='contraventi_est_act_0faf59_idx'),
        ),
        migrations.AddField(
            model_name='contravention',
            name='type_infraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contraventions', to='contraventions.typeinfraction', verbose_name="Type d'infraction"),
        ),
        migrations.AddIndex(
            model_name='contravention',
            index=models.Index(fields=['agent_controleur', 'date_heure_infraction'], name='contraventi_agent_c_a76ced_idx'),
        ),
        migrations.AddIndex(
            model_name='contravention',
            index=models.Index(fields=['vehicule', 'statut'], name='contraventi_vehicul_563463_idx'),
        ),
        migrations.AddIndex(
            model_name='contravention',
            index=models.Index(fields=['conducteur', 'statut'], name='contraventi_conduct_72af77_idx'),
        ),
        migrations.AddIndex(
            model_name='contravention',
            index=models.Index(fields=['statut', 'date_limite_paiement'], name='contraventi_statut_4da64c_idx'),
        ),
        migrations.AddIndex(
            model_name='contravention',
            index=models.Index(fields=['date_heure_infraction'], name='contraventi_date_he_fc6a32_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcontroleurprofile',
            index=models.Index(fields=['matricule'], name='contraventi_matricu_498818_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcontroleurprofile',
            index=models.Index(fields=['user'], name='contraventi_user_id_7f766b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcontroleurprofile',
            index=models.Index(fields=['autorite_type'], name='contraventi_autorit_c7402a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcontroleurprofile',
            index=models.Index(fields=['est_actif'], name='contraventi_est_act_5271de_idx'),
        ),
        migrations.AddIndex(
            model_name='contestation',
            index=models.Index(fields=['numero_contestation'], name='contraventi_numero__05bdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='contestation',
            index=models.Index(fields=['contravention', 'statut'], name='contraventi_contrav_838118_idx'),
        ),
        migrations.AddIndex(
            model_name='contestation',
            index=models.Index(fields=['statut'], name='contraventi_statut_436b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='contraventionauditlog',
            index=models.Index(fields=['contravention', 'timestamp'], name='contraventi_contrav_a6ac30_idx'),
        ),
        migrations.AddIndex(
            model_name='contraventionauditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='contraventi_action__f4af97_idx'),
        ),
        migrations.AddIndex(
            model_name='contraventionauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='contraventi_user_id_a74f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='dossierfourriere',
            index=models.Index(fields=['numero_dossier'], name='contraventi_numero__5e90ab_idx'),
        ),
        migrations.AddIndex(
            model_name='dossierfourriere',
            index=models.Index(fields=['statut'], name='contraventi_statut_74e9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='dossierfourriere',
            index=models.Index(fields=['date_mise_fourriere'], name='contraventi_date_mi_106b25_idx'),
        ),
        migrations.AddIndex(
            model_name='photocontravention',
            index=models.Index(fields=['contravention', 'ordre'], name='contraventi_contrav_f12f3c_idx'),
        ),
    ]
