# Generated by Django 5.2.7 on 2025-11-01 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('type_template', models.CharField(choices=[('rappel_echeance', "Rappel d'échéance"), ('confirmation_paiement', 'Confirmation de paiement'), ('vehicule_ajoute', 'Véhicule ajouté'), ('paiement_echoue', 'Paiement échoué'), ('qr_genere', 'QR code généré'), ('bienvenue', 'Bienvenue')], max_length=50, verbose_name='Type de template')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('mg', 'Malagasy')], max_length=5, verbose_name='Langue')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('contenu_html', models.TextField(verbose_name='Contenu HTML')),
                ('contenu_texte', models.TextField(verbose_name='Contenu texte')),
                ('variables_disponibles', models.JSONField(default=list, help_text='Liste des variables utilisables dans le template', verbose_name='Variables disponibles')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Est actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de notification',
                'verbose_name_plural': 'Templates de notifications',
                'indexes': [models.Index(fields=['type_template', 'langue', 'est_actif'], name='notificatio_type_te_bb1951_idx')],
                'unique_together': {('type_template', 'langue')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('system', 'Système')], max_length=20, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('mg', 'Malagasy')], default='fr', max_length=5, verbose_name='Langue')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Est lue')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_c291d5_idx'), models.Index(fields=['type_notification'], name='notificatio_type_no_ba8ea8_idx'), models.Index(condition=models.Q(('est_lue', False)), fields=['user', 'est_lue'], name='notif_user_non_lue_idx'), models.Index(fields=['date_envoi'], name='notificatio_date_en_1a8f7a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_lecture__isnull', True), ('date_lecture__gte', models.F('date_envoi')), _connector='OR'), name='date_lecture_after_envoi')],
            },
        ),
    ]
