# Generated by Django 5.2.7 on 2025-11-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contenu_fr',
            field=models.TextField(null=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='notification',
            name='contenu_mg',
            field=models.TextField(null=True, verbose_name='Contenu'),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre_mg',
            field=models.CharField(max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='contenu_html_fr',
            field=models.TextField(null=True, verbose_name='Contenu HTML'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='contenu_html_mg',
            field=models.TextField(null=True, verbose_name='Contenu HTML'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='contenu_texte_fr',
            field=models.TextField(null=True, verbose_name='Contenu texte'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='contenu_texte_mg',
            field=models.TextField(null=True, verbose_name='Contenu texte'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du template'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='nom_mg',
            field=models.CharField(max_length=100, null=True, verbose_name='Nom du template'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='sujet_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Sujet'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='sujet_mg',
            field=models.CharField(max_length=200, null=True, verbose_name='Sujet'),
        ),
    ]
