# Generated by Django 5.2.7 on 2025-11-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_contenu_fr_notification_contenu_mg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='contenu_fr',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='contenu_mg',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='titre_fr',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='titre_mg',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='contenu_html_fr',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='contenu_html_mg',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='contenu_texte_fr',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='contenu_texte_mg',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='nom_fr',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='nom_mg',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='sujet_fr',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='sujet_mg',
        ),
    ]
