"""
Cash Receipt Service
Handles receipt generation, printing, and QR code integration
"""

from decimal import Decimal
from io import BytesIO
from typing import Optional, Tuple

from django.contrib.auth.models import User
from django.db import transaction
from django.utils import timezone

import qrcode
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas

from payments.models import (
    CashReceipt,
    CashSystemConfig,
    CashTransaction,
    QRCode,
)

from .cash_audit_service import CashAuditService


class CashReceiptService:
    """Service for generating and managing cash receipts"""

    @staticmethod
    @transaction.atomic
    def generate_cash_receipt(
        cash_transaction: CashTransaction, request=None
    ) -> Tuple[Optional[CashReceipt], Optional[str]]:
        """
        Generate receipt with QR code for a cash transaction

        Args:
            cash_transaction: The cash transaction
            request: HTTP request object for audit logging

        Returns:
            Tuple of (CashReceipt, error_message)
        """
        try:
            # Check if receipt already exists
            if hasattr(cash_transaction, "receipt"):
                return cash_transaction.receipt, None

            # Get or create QR code for the payment
            # This integrates with the existing QRCode model used for all payment types
            payment = cash_transaction.payment
            vehicle = payment.vehicule_plaque

            # Get or create QR code - reuses existing QR codes if already generated
            # for this vehicle and tax year (e.g., from online payments)
            qr_code, created = QRCode.objects.get_or_create(
                vehicule_plaque=vehicle,
                annee_fiscale=payment.annee_fiscale,
                defaults={
                    "date_expiration": timezone.now() + timezone.timedelta(days=365),
                    "est_actif": True,
                },
            )

            # If QR code was just created, it will have a unique token generated by the model
            # If it already existed (from online payment), we reuse the same QR code
            # This ensures consistency across all payment methods

            # Generate QR code data
            qr_data = CashReceiptService._generate_qr_data(cash_transaction, qr_code)

            # Create CashReceipt record
            receipt = CashReceipt.objects.create(
                transaction=cash_transaction,
                qr_code=qr_code,
                vehicle_registration=cash_transaction.vehicle_plate,
                vehicle_owner=cash_transaction.customer_name,
                tax_year=payment.annee_fiscale,
                tax_amount=cash_transaction.tax_amount,
                amount_paid=cash_transaction.amount_tendered,
                change_given=cash_transaction.change_given,
                collector_name=cash_transaction.collector.full_name,
                collector_id=cash_transaction.collector.agent_id,
                payment_date=cash_transaction.transaction_time,
                qr_code_data=qr_data,
            )

            # Mark receipt as printed
            cash_transaction.receipt_printed = True
            cash_transaction.receipt_print_time = timezone.now()
            cash_transaction.save(update_fields=["receipt_printed", "receipt_print_time"])

            # Create audit log
            audit_service = CashAuditService()
            audit_service.log_action(
                action_type="receipt_print",
                user=cash_transaction.collector.user,
                session=cash_transaction.session,
                transaction=cash_transaction,
                data={
                    "receipt_number": receipt.receipt_number,
                    "vehicle_plate": receipt.vehicle_registration,
                    "tax_amount": str(receipt.tax_amount),
                },
                request=request,
            )

            return receipt, None

        except Exception as e:
            return None, f"Erreur lors de la génération du reçu: {str(e)}"

    @staticmethod
    def _generate_qr_data(cash_transaction: CashTransaction, qr_code: QRCode) -> str:
        """
        Generate QR code data string compatible with existing QR verification system

        Args:
            cash_transaction: The cash transaction
            qr_code: The QR code object

        Returns:
            QR code data string
        """
        payment = cash_transaction.payment

        # Use the existing QR code token format for compatibility with verification system
        # The QR code token is already generated by the QRCode model
        # Format: token for verification via existing QR verification views
        return qr_code.token

    @staticmethod
    @transaction.atomic
    def reprint_receipt(
        original_receipt: CashReceipt, requested_by: User, request=None
    ) -> Tuple[Optional[CashReceipt], Optional[str]]:
        """
        Reprint existing receipt (marked as duplicate)

        Args:
            original_receipt: The original receipt to reprint
            requested_by: The user requesting the reprint
            request: HTTP request object for audit logging

        Returns:
            Tuple of (duplicate CashReceipt, error_message)
        """
        try:
            # Create duplicate receipt
            duplicate_receipt = CashReceipt.objects.create(
                transaction=original_receipt.transaction,
                qr_code=original_receipt.qr_code,
                vehicle_registration=original_receipt.vehicle_registration,
                vehicle_owner=original_receipt.vehicle_owner,
                tax_year=original_receipt.tax_year,
                tax_amount=original_receipt.tax_amount,
                amount_paid=original_receipt.amount_paid,
                change_given=original_receipt.change_given,
                collector_name=original_receipt.collector_name,
                collector_id=original_receipt.collector_id,
                payment_date=original_receipt.payment_date,
                qr_code_data=original_receipt.qr_code_data,
                is_duplicate=True,
                original_receipt=original_receipt,
            )

            # Create audit log
            audit_service = CashAuditService()
            audit_service.log_action(
                action_type="receipt_reprint",
                user=requested_by,
                session=original_receipt.transaction.session,
                transaction=original_receipt.transaction,
                data={
                    "original_receipt_number": original_receipt.receipt_number,
                    "duplicate_receipt_number": duplicate_receipt.receipt_number,
                    "vehicle_plate": duplicate_receipt.vehicle_registration,
                },
                request=request,
            )

            return duplicate_receipt, None

        except Exception as e:
            return None, f"Erreur lors de la réimpression du reçu: {str(e)}"

    @staticmethod
    def generate_cash_receipt_pdf(receipt: CashReceipt) -> BytesIO:
        """
        Generate printable PDF receipt using ReportLab

        Args:
            receipt: The cash receipt

        Returns:
            BytesIO buffer containing the PDF
        """
        buffer = BytesIO()

        # Create PDF canvas
        p = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4

        # Set up fonts and positions
        y_position = height - 50 * mm
        left_margin = 30 * mm

        # Header
        p.setFont("Helvetica-Bold", 16)
        p.drawString(left_margin, y_position, "REÇU DE PAIEMENT DE TAXE")
        y_position -= 10 * mm

        # Duplicate watermark if applicable
        if receipt.is_duplicate:
            p.setFont("Helvetica-Bold", 12)
            p.setFillColorRGB(0.8, 0, 0)
            p.drawString(left_margin, y_position, "*** DUPLICATA ***")
            p.setFillColorRGB(0, 0, 0)
            y_position -= 8 * mm

        # Receipt information
        p.setFont("Helvetica", 10)
        p.drawString(left_margin, y_position, f"Numéro de reçu: {receipt.receipt_number}")
        y_position -= 6 * mm
        p.drawString(left_margin, y_position, f"Date: {receipt.payment_date.strftime('%d/%m/%Y %H:%M')}")
        y_position -= 10 * mm

        # Vehicle information
        p.setFont("Helvetica-Bold", 12)
        p.drawString(left_margin, y_position, "Informations du véhicule")
        y_position -= 6 * mm

        p.setFont("Helvetica", 10)
        p.drawString(left_margin, y_position, f"Immatriculation: {receipt.vehicle_registration}")
        y_position -= 6 * mm
        p.drawString(left_margin, y_position, f"Propriétaire: {receipt.vehicle_owner}")
        y_position -= 6 * mm
        p.drawString(left_margin, y_position, f"Année fiscale: {receipt.tax_year}")
        y_position -= 10 * mm

        # Payment information
        p.setFont("Helvetica-Bold", 12)
        p.drawString(left_margin, y_position, "Détails du paiement")
        y_position -= 6 * mm

        p.setFont("Helvetica", 10)
        p.drawString(left_margin, y_position, f"Montant de la taxe: {receipt.tax_amount:,.2f} Ar")
        y_position -= 6 * mm
        p.drawString(left_margin, y_position, f"Montant payé: {receipt.amount_paid:,.2f} Ar")
        y_position -= 6 * mm
        p.drawString(left_margin, y_position, f"Monnaie rendue: {receipt.change_given:,.2f} Ar")
        y_position -= 10 * mm

        # Collector information
        p.setFont("Helvetica-Bold", 12)
        p.drawString(left_margin, y_position, "Agent collecteur")
        y_position -= 6 * mm

        p.setFont("Helvetica", 10)
        p.drawString(left_margin, y_position, f"Nom: {receipt.collector_name}")
        y_position -= 6 * mm
        p.drawString(left_margin, y_position, f"ID: {receipt.collector_id}")
        y_position -= 10 * mm

        # Generate QR code image
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(receipt.qr_code_data)
        qr.make(fit=True)

        qr_img = qr.make_image(fill_color="black", back_color="white")
        qr_buffer = BytesIO()
        qr_img.save(qr_buffer, format="PNG")
        qr_buffer.seek(0)

        # Add QR code to PDF
        p.setFont("Helvetica-Bold", 12)
        p.drawString(left_margin, y_position, "Code QR de vérification")
        y_position -= 50 * mm

        qr_image = ImageReader(qr_buffer)
        p.drawImage(qr_image, left_margin, y_position, width=40 * mm, height=40 * mm)
        y_position -= 15 * mm

        # Footer
        config = CashSystemConfig.get_config()
        if config.receipt_footer_text:
            p.setFont("Helvetica", 8)
            p.drawString(left_margin, y_position, config.receipt_footer_text)

        # Finalize PDF
        p.showPage()
        p.save()

        buffer.seek(0)
        return buffer

    @staticmethod
    def get_receipt_by_number(receipt_number: str) -> Optional[CashReceipt]:
        """
        Get receipt by receipt number

        Args:
            receipt_number: The receipt number

        Returns:
            CashReceipt or None
        """
        try:
            return CashReceipt.objects.get(receipt_number=receipt_number)
        except CashReceipt.DoesNotExist:
            return None

    @staticmethod
    def get_receipts_for_vehicle(vehicle_plate: str, tax_year: Optional[int] = None):
        """
        Get all receipts for a vehicle

        Args:
            vehicle_plate: The vehicle plate number
            tax_year: Optional tax year filter

        Returns:
            QuerySet of CashReceipt objects
        """
        receipts = CashReceipt.objects.filter(vehicle_registration=vehicle_plate)

        if tax_year:
            receipts = receipts.filter(tax_year=tax_year)

        return receipts.order_by("-payment_date")
